const Events = {
  DROP_DOWN_VALUE_CHANGED: "DROP_DOWN_VALUE_CHANGED",
  FINISH_BUTTON_CLICKED: "FINISH_BUTTON_CLICKED",
  HISTORY_DIALOG_VIEW_CLOSED: "HISTORY_DIALOG_VIEW_CLOSED",
  PREVIOUS_STATE_CLICKED: "PREVIOUS_STATE_CLICKED",
  LOGIN_BUTTON_CLICKED: "LOGIN_BUTTON_CLICKED"
};

export default Events;